### ISSUE TITLE
Ingame error when menus are open

### ISSUE THREAD

**Issue by HeadhunterXamd** [Vermintide-Mod-Framework/Grasmann-Mods#3]
Since the 1.2.1 patch everytime there is a menu/GUI with buttons open I get spammed by error messages about the global close_pressed ([line 38](https://github.com/Vermintide-Mod-Framework/Grasmann-Mods/blob/fc1a391fe6c95e8bb66e375e0da8e78041a174ca/ui_improvements/scripts/mods/ui_improvements/ui_improvements_achievements.lua#L38) of the ui_improvements_achievements.lua file) not being defined.

**Comment by grasmann** [comment]
This has been fixed a while ago.
